### ISSUE TITLE
Unable to run codecov command

### ISSUE THREAD

**Issue by meandavejustice** [mozilla-lockbox/lockbox-addon#51]
Was trying to take a look at the current code coverage, but ran into some errors trying to run `npm run codecov`.

Looks like it just isn't generating any reports. Tried with both 2.7 and 3.5.2 aliased to `python`

Here is my output:
```
meandave@LAPTOP-NA0Q0G86:/mnt/c/Users/Dave Justice/Code/lockbox-addon$ npm run codecov

> lockbox@2.0.0-alpha codecov /mnt/c/Users/Dave Justice/Code/lockbox-addon
> codecov

  _____          _
 / ____|        | |
| |     ___   __| | ___  ___ _____   __
| |    / _ \ / _` |/ _ \/ __/ _ \ \ / /
| |___| (_) | (_| |  __/ (_| (_) \ V /
 \_____\___/ \__,_|\___|\___\___/ \_/
                                v3.1.0
==> Detecting CI Provider
    No CI Detected. Using git/mercurial
==> Configuration:
    Endpoint: https://codecov.io
{ commit: '361f902277107c765707e2b9ab1ed873892f1091',
  branch: 'specify-node-version',
  package: 'node-v3.1.0' }
==> Building file structure
==> Generating gcov reports (skip via --disable=gcov)
    $ find /mnt/c/Users/Dave Justice/Code/lockbox-addon -type f -name '*.gcno'  -exec gcov  {} +
find: ‘/mnt/c/Users/Dave’: No such file or directory
find: ‘Justice/Code/lockbox-addon’: No such file or directory
    Failed to run gcov command.
==> Scanning for reports
find: ‘/mnt/c/Users/Dave’: No such file or directory
find: ‘Justice/Code/lockbox-addon’: No such file or directory
child_process.js:662
    throw err;
    ^

Error: Command failed: find /mnt/c/Users/Dave Justice/Code/lockbox-addon -type f \( -name '*coverage.*' -or -name 'nosetests.xml' -or -name 'jacoco*.xml' -or -name 'clover.xml' -or -name 'report.xml' -or -name 'cobertura.xml' -or -name 'luacov.report.out' -or -name 'lcov.info' -or -name '*.lcov' -or -name 'gcov.info' -or -name '*.gcov' -or -name '*.lst' \) -not -name '*.sh' -not -name '*.data' -not -name '*.py' -not -name '*.class' -not -name '*.xcconfig' -not -name 'Coverage.profdata' -not -name 'phpunit-code-coverage.xml' -not -name 'coverage.serialized' -not -name '*.pyc' -not -name '*.cfg' -not -name '*.egg' -not -name '*.whl' -not -name '*.html' -not -name '*.js' -not -name '*.cpp' -not -name 'coverage.jade' -not -name 'include.lst' -not -name 'inputFiles.lst' -not -name 'createdFiles.lst' -not -name 'coverage.html' -not -name 'scoverage.measurements.*' -not -name 'test_*_coverage.txt' -not -path '*/vendor/*' -not -path '*/htmlcov/*' -not -path '*/home/cainus/*' -not -path '*/virtualenv/*' -not -path '*/js/generated/coverage/*' -not -path '*/.virtualenv/*' -not -path '*/virtualenvs/*' -not -path '*/.virtualenvs/*' -not -path '*/.env/*' -not -path '*/.envs/*' -not -path '*/env/*' -not -path '*/envs/*' -not -path '*/.venv/*' -not -path '*/.venvs/*' -not -path '*/venv/*' -not -path '*/venvs/*' -not -path '*/.git/*' -not -path '*/.hg/*' -not -path '*/.tox/*' -not -path '*/__pycache__/*' -not -path '*/.egg-info*' -not -path '*/$bower_components/*' -not -path '*/node_modules/*' -not -path '*/conftest_*.c.gcov'
find: ‘/mnt/c/Users/Dave’: No such file or directory
find: ‘Justice/Code/lockbox-addon’: No such file or directory

    at checkExecSyncError (child_process.js:622:11)
    at execSync (child_process.js:659:13)
    at Object.upload (/mnt/c/Users/Dave Justice/Code/lockbox-addon/node_modules/codecov/lib/codecov.js:471:16)
    at Object.<anonymous> (/mnt/c/Users/Dave Justice/Code/lockbox-addon/node_modules/codecov/bin/codecov:27:9)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:774:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lockbox@2.0.0-alpha codecov: `codecov`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lockbox@2.0.0-alpha codecov script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/meandave/.npm/_logs/2019-01-08T15_09_10_853Z-debug.log
```

**Comment by meandavejustice** [comment]
@lmorchard I was able to get the coverage results after running tests and navigating to `coverage/html` and serving with an http server.

The `codecov` command is still giving me the same errors after using the symlink above. This is an issue very personalized to my machine, and I have a workaround so I'm gunna go ahead and close this. Thanks for the help!
